version: "3.9"
services:
  database:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_DB: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432"
    restart: unless-stopped
  backend:
    build: .
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "8080"
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000"
    restart: unless-stopped
    links:
      - backend
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    links:
      - frontend
