version: "3.9"
services:
  database:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_DB: catpics
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped
