version: "3.9"
services:
  database:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_DB: catpics
      POSTGRES_PASSWORD: password # change it
    ports:
      - "5432"
    restart: unless-stopped
  backend:
    build: .
    ports:
      - "8080"
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000"
    restart: always
    links:
      - backend
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    links:
      - frontend
