version: "3.9"
services:
  database:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_DB: catpics
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped
  backend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8080"
      - "8000:8000"
    volumes:
      - ./files:/files
    restart: unless-stopped
    links:
      - database
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - "3000"
    volumes:
      - ./frontend:/frontend
    restart: unless-stopped
    links:
      - backend
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-dev
    ports:
      - "8080:80"
    restart: unless-stopped
    links:
      - frontend
